# -*- coding: utf-8 -*-
"""game_score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOPaSi8xVwqKOgMO70CW3ECfC79vvLbF
"""

player_name = input("Enter player name: ")
games_played = int(input("Enter number of games played: "))
total_score = int(input("Enter total score: "))
average_score = total_score / games_played
print(f"Player: {player_name}")
print(f"Games Played: {games_played}")
print(f"Total Score: {total_score}")
print(f"Average Score: {average_score}")